import io.vavr.collection.Stream;

import java.util.Map;

public class Day2RPC {

    public static void main(String[] args) {
        String testInput = "A Y\nB X\nC Z";

        Day2RPC day2 = new Day2RPC();
        day2.bestStrategy(testInput);

        String mainInput = "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "C X\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "C X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "B Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "A X\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "C X\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B X\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "C X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "B X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "B X\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "B X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "C X\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "B Z\n" +
                "B Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C X\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C X\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "B Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "B Y\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "B X\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C X\n" +
                "B Y\n" +
                "B X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C X\n" +
                "C X\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n";

        day2.bestStrategy(mainInput);


        day2.forceStrategy(testInput);
day2.forceStrategy(mainInput);


    }


    interface Thing {
              
        boolean winsFrom(Thing thing);
        default boolean ties(Thing thing) {
          return this.getClass().equals(thing.getClass());
        }
    }

    record Rock() implements Thing {

        @Override
        public boolean winsFrom(Thing thing) {
            return thing.getClass().equals(Scissors.class);
        }
    }

    record Paper() implements Thing {

        @Override
        public boolean winsFrom(Thing thing) {
            return thing.getClass().equals(Rock.class);
        }
    }

    record Scissors() implements Thing {

        @Override
        public boolean winsFrom(Thing thing) {
            return thing.getClass().equals(Paper.class);
        }
    }

    Map<String, Thing> opponent = Map.of(
            "A", new Rock(),
            "B", new Paper(),
            "C", new Scissors()
    );

    Map<String, Thing> you = Map.of(
            "X", new Rock(),
            "Y", new Paper(),
            "Z", new Scissors()
    );

    Map<Thing, Thing> winsFrom = Map.of(
            new Rock(), new Paper(),
            new Paper(), new Scissors(),
            new Scissors(), new Rock()
    );
    Map<Thing, Thing> losesFrom = Map.of(
            new Rock(), new Scissors(),
            new Scissors(), new Paper(),
            new Paper(), new Rock()
            );

    Map<Thing, Integer> score = Map.of(
            new Rock(), 1,
            new Paper(), 2,
            new Scissors(), 3
    );
    private void bestStrategy(String testInput) {
        Number result = Stream.ofAll(testInput.lines())
                .map(s -> s.split(" "))
                .map(l -> {
                    Thing opp = opponent.get(l[0]);
                    Thing y = you.get(l[1]);

                    return calculateScore(opp, y);
                }).sum();


        System.out.println(result);
    }



    private void forceStrategy(String testInput) {
        Number result = Stream.ofAll(testInput.lines())
                .map(s -> s.split(" "))
                .map(l -> {
                    Thing opp = opponent.get(l[0]);

                    Thing y = switch (l[1]) {
                        case "X" -> losesFrom.get(opp);
                        case "Y" -> ties(opp);
                        case "Z" -> winsFrom.get(opp);
                        default -> throw new RuntimeException();
                    };

                    return calculateScore(opp, y);
                }).sum();


        System.out.println(result);
    }

    private static Thing ties(Thing opp) {
        return opp;
    }

    private Integer calculateScore(Thing opp, Thing y) {
        if (y.winsFrom(opp)) {
            int s = score.get(y) + 6;
            System.out.println("WIN " + s + " FROM " + opp + " vs " + y);
            return s;
        } else if (y.ties(opp)) {
            int s = score.get(y) + 3;
            System.out.println("TIE " + s + " FROM " + opp + " vs " + y);
            return s;
        } else {
            Integer s = score.get(y);
            System.out.println("LOSS  " + s + " FROM " + opp + " vs " + y);
            return s;
        }
    }

}
